# Generated by Django 5.2.17 on 2026-09-28 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pdf", models.FileField(upload_to="decks/%Y/%m/")),
                ("page_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audio", models.FileField(upload_to="recordings/%Y/%m/")),
                ("duration_ms", models.PositiveIntegerField()),
                ("slide_events", models.JSONField(default=list)),
                ("audience", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transcript", models.JSONField(blank=True, null=True)),
                ("feedback", models.JSONField(default=list)),
                ("error", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="rehearsals.deck",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_index", models.PositiveIntegerField()),
                ("image", models.FileField(upload_to="slides/%Y/%m/")),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="rehearsals.deck",
                    ),
                ),
            ],
            options={
                "ordering": ["slide_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deck", "slide_index"), name="unique_deck_slide"
                    )
                ],
            },
        ),
    ]
