# Generated by Django 5.2.17 on 2026-10-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='upload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='deck',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='preparation_version',
            field=models.CharField(default='pdfium-v1', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('content_hash', 'preparation_version'), name='unique_prepared_pdf'),
        ),
    ]
