# Generated by Django 5.2.17 on 2026-10-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0002_attempt_upload_hash_deck_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='feedback_state',
            field=models.CharField(default='disabled', max_length=24),
        ),
        migrations.AddField(
            model_name='attempt',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='transcription_meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='transcription_state',
            field=models.CharField(default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='attempt',
            name='visits',
            field=models.JSONField(default=list),
        ),
    ]
