# Generated by Django 5.2.17 on 2026-10-08 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0002_attempt_upload_hash_deck_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='analysis_outcome',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='attempt',
            name='claim_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='failed_stage',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='attempt',
            name='feedback_state',
            field=models.CharField(default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='attempt',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='processing_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='processing_state',
            field=models.CharField(db_index=True, default='awaiting_analysis', max_length=32),
        ),
        migrations.AddField(
            model_name='attempt',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='visits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProviderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('claim_token', models.UUIDField()),
                ('provider', models.CharField(default='openai', max_length=32)),
                ('model', models.CharField(default='whisper-1', max_length=32)),
                ('input_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('raw_received_at', models.DateTimeField(null=True)),
                ('outcome', models.CharField(default='submitted', max_length=32)),
                ('raw_response', models.JSONField(null=True)),
                ('usage', models.JSONField(null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_requests', to='rehearsals.attempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'generation'), name='one_provider_request_per_generation')],
            },
        ),
    ]
