# Generated by Django 5.2.17 on 2026-10-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0003_attempt_feedback_state_attempt_metrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=80)),
                ('version', models.CharField(max_length=40)),
                ('state', models.CharField(default='pending', max_length=24)),
                ('result', models.JSONField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProject',
            fields=[
                ('id', models.CharField(max_length=160, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='feedback_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attempt',
            name='feedback_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='analysis_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='deck',
            name='description_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='descriptions',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ProviderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=24)),
                ('state', models.CharField(default='started', max_length=24)),
                ('reserved_tokens', models.PositiveIntegerField(default=0)),
                ('usage', models.JSONField(default=dict)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='rehearsals.generation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='rehearsals.providerproject')),
            ],
        ),
    ]
