# Generated by Django 5.2.17 on 2026-10-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0004_generation_providerproject_attempt_feedback_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description_source_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='deck',
            name='descriptions_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerproject',
            name='not_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
