# Generated by Django 5.2.17 on 2026-10-08 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0004_preserve_existing_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=16)),
                ('project_id', models.CharField(max_length=160)),
                ('model', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=40)),
                ('schema_version', models.CharField(max_length=40)),
                ('source_snapshot', models.JSONField()),
                ('prompt_digest', models.CharField(max_length=64)),
                ('input_hash', models.CharField(max_length=64)),
                ('processing_revision', models.PositiveIntegerField(default=0)),
                ('description_revision', models.PositiveIntegerField(default=0)),
                ('descriptions', models.JSONField(null=True)),
                ('edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='description_sets', to='rehearsals.deck')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('description_revision', models.PositiveIntegerField()),
                ('state', models.CharField(db_index=True, default='queued', max_length=32)),
                ('claim_token', models.UUIDField(null=True)),
                ('queued_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('retry_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('description_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='rehearsals.descriptionset')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQuotaBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('project_id', models.CharField(max_length=160)),
                ('model', models.CharField(max_length=100)),
                ('blocked_until', models.DateTimeField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'project_id', 'model'), name='unique_feedback_quota_bucket')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('claim_token', models.UUIDField()),
                ('provider', models.CharField(max_length=16)),
                ('project_id', models.CharField(max_length=160)),
                ('model', models.CharField(max_length=100)),
                ('stage', models.CharField(default='descriptions', max_length=24)),
                ('input_hash', models.CharField(max_length=64)),
                ('queued_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(null=True)),
                ('received_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('outcome', models.CharField(default='local', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('status_code', models.PositiveIntegerField(null=True)),
                ('raw_body', models.BinaryField(null=True)),
                ('body_complete', models.BooleanField(null=True)),
                ('body_issue', models.CharField(max_length=40, null=True)),
                ('retry_at', models.DateTimeField(null=True)),
                ('usage', models.JSONField(null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='request', to='rehearsals.descriptionjob')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveBigIntegerField()),
                ('reserved_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(null=True)),
                ('released_at', models.DateTimeField(null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rehearsals.feedbackquotabucket')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='rehearsals.feedbackrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='descriptionset',
            constraint=models.UniqueConstraint(fields=('deck', 'source_fingerprint', 'provider', 'project_id', 'model', 'prompt_version', 'schema_version'), name='unique_description_scope'),
        ),
        migrations.AddConstraint(
            model_name='descriptionjob',
            constraint=models.UniqueConstraint(fields=('description_set', 'generation'), name='unique_description_generation'),
        ),
    ]
