# Generated by Django 5.2.17 on 2026-10-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0005_descriptionset_descriptionjob_feedbackquotabucket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrequest',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request', to='rehearsals.descriptionjob'),
        ),
        migrations.CreateModel(
            name='FeedbackAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coaching', to='rehearsals.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('description_generation', models.PositiveIntegerField()),
                ('description_revision', models.PositiveIntegerField(null=True)),
                ('source_snapshot', models.JSONField()),
                ('descriptions_snapshot', models.JSONField(null=True)),
                ('prompt_version', models.CharField(max_length=40)),
                ('schema_version', models.CharField(max_length=40)),
                ('prompt_digest', models.CharField(max_length=64)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('result', models.JSONField(null=True)),
                ('state', models.CharField(db_index=True, default='waiting_descriptions', max_length=32)),
                ('claim_token', models.UUIDField(null=True)),
                ('queued_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('retry_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='rehearsals.feedbackanalysis')),
                ('description_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_jobs', to='rehearsals.descriptionset')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='coaching_job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request', to='rehearsals.feedbackjob'),
        ),
        migrations.AddConstraint(
            model_name='feedbackrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coaching_job__isnull', True), ('job__isnull', False), ('stage', 'descriptions')), models.Q(('coaching_job__isnull', False), ('job__isnull', True), ('stage', 'coaching')), _connector='OR'), name='feedback_request_exact_stage_owner'),
        ),
        migrations.AddConstraint(
            model_name='feedbackjob',
            constraint=models.UniqueConstraint(fields=('analysis', 'generation'), name='unique_coaching_generation'),
        ),
    ]
